### ISSUE TITLE
Update README to point to Sonatype, and remove references to bintray

### ISSUE THREAD

**Issue by namirfa** [Vantiq/vantiq-sdk-java#17]

**Comment by steve-langley** [comment]
Just FYI, I will need to know when the library is published and what edits I need to make the the build.gradle to stop referencing bintray. (The Android app won't build until this gets updated.)

**Comment by namirfa** [comment]
> Just FYI, I will need to know when the library is published and what edits I need to make the the build.gradle to stop referencing bintray. (The Android app won't build until this gets updated.)

I'll make sure to keep you in the loop, Steve. Still waiting to hear back from them.
